#!/bin/bash
DIFB_SUBCMD_INCLUDE_EJECT="ON"
BKGREP_EXEC_FILE_DIR=$(cd $(dirname $0) ; pwd)
. ${BKGREP_EXEC_FILE_DIR}/difbk
pip_swich=0
first_para="${1}"
second_para="${2}"
third_para="${3}"
check_first_para=$(echo "${first_para}"  | grep -E "/${BUCK_UP_DIR_NAME}/[0-9]{4}/[0-9]{2}/[0-9]{2}/" || e=$? )
if [ -n "${check_first_para}" ];then 
	dfbk_property_contents=$(cat "${DFBK_PROPERTY_FILE_PATH}")
	DFBK_SEARCH_WORD=$(echo "${dfbk_property_contents}" | sed 's/'${DFBK_PROPERTY_SEARCH_WORD_TITLE}'\=//')
	lecho "${DFBK_SEARCH_WORD}"
	first_val=${DFBK_SEARCH_WORD}
	second_val=${first_para}
	third_para=${second_para}
else
	first_val=${first_para}
	second_val=${second_para}
fi
lecho second_para:${second_para}
lecho second_val:${second_val}
if expr "${second_val}" : "-\?[0-9]*$" >&/dev/null;then 
 	if [ $((${second_val} / 10)) -eq 0 ];then
 		lecho /10 
 		third_val=${second_val}
 	fi
else 
	third_val=${third_para}
fi
lecho third_val: ${third_val}
if [ -z "${third_val}" ];then third_val=2; fi
lecho third_val2:${third_val}
if [ -z "${second_val}" ];then second_val="$(cat /dev/stdin)": pip_swich=1; fi
# no para alert
if [ -z "${first_val}" ] || [ -z "${second_val}" ] ;then echo "non para (first_para: ${first_para}, second_para: ${second_para}"; exit 0;fi
lecho "zgrep -A 2 -B 2 -n \"${first_val}\" ${second_val}"
if [ ${pip_swich} -eq 1 ];then 
	bkep_disp_contents=$(zgrep  -A ${third_val} -B ${third_val} --color -Ein "${first_val}" <(echo "${second_val}"))
	bke_disp_con_num=$(echo "${bkep_disp_contents}" | wc -l)
	if [ ${bke_disp_con_num} -gt ${LESS_BORDER_NUM} ];then
		echo "${bkep_disp_contents}" | sed -r "s/(${first_val})/\x1b[1;38;5;20m\1\x1b[0m/gi" | sed -r "s/(^[0-9]{1,6}:)/\x1b[1;38;5;20m\1\x1b[0m/g" | sed -r "s/(^[0-9]{1,6}-)/\x1b[38;5;2m\1\x1b[0m/g" | less -R
	else
		echo "${bkep_disp_contents}" | sed -r "s/(${first_val})/\x1b[1;38;5;20m\1\x1b[0m/gi" | sed -r "s/(^[0-9]{1,6}:)/\x1b[1;38;5;20m\1\x1b[0m/g" | sed -r "s/(^[0-9]{1,6}-)/\x1b[38;5;2m\1\x1b[0m/g"
	fi
else
	bkep_disp_contents=$(cat <(echo "### ${second_val}") <(echo "--") <(zgrep  -A ${third_val} -B ${third_val} --color -Ein "${first_val}" "${second_val}"))
	bke_disp_con_num=$(echo "${bkep_disp_contents}" | wc -l)
	if [ ${bke_disp_con_num} -gt ${LESS_BORDER_NUM} ];then
		echo "${bkep_disp_contents}" | sed -r "s/(${first_val})/\x1b[1;38;5;20m\1\x1b[0m/gi" | sed -r "s/(^[0-9]{1,6}:)/\x1b[1;38;5;20m\1\x1b[0m/g" | sed -r "s/(^[0-9]{1,6}-)/\x1b[38;5;2m\1\x1b[0m/g" | less -R
	else 
		echo "${bkep_disp_contents}" | sed -r "s/(${first_val})/\x1b[1;38;5;20m\1\x1b[0m/gi" | sed -r "s/(^[0-9]{1,6}:)/\x1b[1;38;5;20m\1\x1b[0m/g" | sed -r "s/(^[0-9]{1,6}-)/\x1b[38;5;2m\1\x1b[0m/g"
	fi
fi