#!/bin/bash
DIFB_SUBCMD_INCLUDE_EJECT="ON"
insert_time_on=0
BKGREP_EXEC_FILE_DIR=$(cd $(dirname $0) ; pwd)
. ${BKGREP_EXEC_FILE_DIR}/difbk
pip_swich=0
first_para="${DIFBK_SUB_CMD}"
if [ -z "${first_para}" ];then exit 0;fi
target_path=$(echo "${first_para}" | grep -oE ".*${BUCK_UP_DIR_NAME}/[0-9]{4}/[0-9]{2}/[0-9]{2}/[0-9]{4}" | sed 's/$/\/'${BUCKUP_DESC_FILE_NAME}'/' | sed 's/\/\//\//g')
[ -z "${target_path}" ] && echo "no desk file path" && exit 0
[ ! -e "$(dirname "${target_path}")" ] && echo "no exist file path"  && exit 0
[ ! -e "${target_path}" ] && insert_time_on=1
nano "${target_path}"; wait 
[[ ! -e ${target_path} ]] && exit 0
echo "$(cat  ${target_path} | tr -d '\n')"  > "${target_path}"
if [ ${insert_time_on} -eq 1 ];then
	time_prefix=$(echo "${first_para}" | rga -o ".*${BUCK_UP_DIR_NAME}/[0-9]{4}/[0-9]{2}/[0-9]{2}/[0-9]{4}" | rga -o "[0-9]{4}/[0-9]{2}/[0-9]{2}/[0-9]{4}$" | sed 's/\//\\\//g')
	sed -e 's/^/'${time_prefix}': /' -i "${target_path}"
fi