#!/bin/bash

set -eu
LANG=C
DIFBK_SUB_CMD="${1}"
readonly EXEC_FILE_DIR=$(cd $(dirname $0) ; pwd)
# incdule diffbk ------------------------
readonly DIFBK_DIR_PATH="${EXEC_FILE_DIR}/difbk_dir"
readonly DIFBK_LIB_DIR_PATH="${DIFBK_DIR_PATH}/difbk_lib"
readonly DIFBK_COMMON_LIB_PATH="${DIFBK_LIB_DIR_PATH}/common_lib"
. "${DIFBK_COMMON_LIB_PATH}/substitute_unique_con_by_comparing_two.sh"
. "${DIFBK_COMMON_LIB_PATH}/echo_desk_rga_cmd.sh"
. "${DIFBK_COMMON_LIB_PATH}/echo_before_and_after_delete_cmd.sh"
. "${DIFBK_COMMON_LIB_PATH}/desk_cat_func.sh"
. "${DIFBK_COMMON_LIB_PATH}/echo_desk_rga_v_cmd.sh"
. "${DIFBK_COMMON_LIB_PATH}/wait_spin.sh"
readonly DIFBK_SCH_LIB_DIR_PATH="${DIFBK_DIR_PATH}/difbk_sch_func"
readonly DIFBK_ROOT_LIB_PATH="${DIFBK_LIB_DIR_PATH}/root_lib"
. "${DIFBK_ROOT_LIB_PATH}/read_args.sh"
. "${DIFBK_ROOT_LIB_PATH}/make_target_dir_name_and_path.sh"
readonly DIFBK_EXEC_DIR_PATH="${DIFBK_DIR_PATH}/difbk_exec"
readonly DIFBK_EXEC_LABEL_SELECT_FILE_PATH=${DIFBK_EXEC_DIR_PATH}/difbk_label_select.sh

readonly CHECH_SUM_DIR_INFO="ddddd"
# ----------------------------------------
# difinition valiable2 -------------------
readonly DIFBK_SCH_CMD_VALIABLE="sch"
readonly DIFBK_DIFF_CMD_VALIABLE="diff"
readonly DIFBK_BK_CMD_VALIABLE="bk"
readonly DIFBK_ST_CMD_VALIABLE="st"
readonly DIFBK_LRS_CMD_VALIABLE="lrs"
readonly DIFBK_RS_CMD_VALIABLE="rs"
readonly DIFBK_CLEAN_CMD_VALIABLE="clean"
readonly DIFBK_MRG_CMD_VALIABLE="mrg"
readonly DIFBK_HELP_CMD_VALIABLE="help"
readonly DIFBK_BLANK_MARK="DIFBK_BLANK_MARK"
readonly DISPLAY_NUM_LIST=30
readonly SED_TTTTBBBB="ttttbbbb"
readonly GGIP_EXETEND=".gz"
readonly DFBK_GGIP_EXETEND=".difbk.gz"
readonly DESC_PREFIX=":desk:"
readonly DIFBK_EXCLUDE_DS_STORE='.DS_Store'
readonly SEPARATE_BAR="###################################################"

# difinition valiable2 --------------------

readonly LSLABEL_ARGS="-lslabel"
readonly RMLABEL_ARGS="-rmlabel"
readonly MKLABEL_ARGS="-mklabel"
readonly FULL_OPTION_NAME="-full"
readonly BUCKUP_CLEAN_ARGS_NAME="-dddd"
readonly LATEST_MERGE_LIST_VALIDATE_ARGS_NAME="-vl"
readonly ALT_ARGS_NAME="-alt"
readonly DEST_ARGS_NAME="-dest"
readonly DRY_BK_ARGS_NAME="-dry-bk"
readonly CUR_DIFF_ARGS_NAME="-cur-diff"
readonly OLD_PREFIX="old"
SHIFT_SEED=0
C_OPTION=""
B_OPTION=""
D_OPTION=""
E_OPTION=""
DA_OPTION=""
DB_OPTION=""
DN_OPTION=""
DV_OPTION=""
dRGA_OPTION=""
GENERAL_OPTION=""
V_OPTION=""
O_OPTION=""
LN_OPTION=""
J_OPTION=""
FULL_OPTION=""
DRY_BK_OPTION=""
CUR_DIFF_OPTION=""
DIFBK_ARGUMENT=""
DIFBK_ARGUMENT_LIST=""
DELETE_SUPPER_ORDER_NUM_FOR_MERGE_LIST=""
LATEST_MERGE_LIST_VALIDATE_ARGS_OPTION=""
MRG_TARGET_DIR_NAME=""
MRG_BUCKUP_DIR_NAME=""
DEST_PAR_DIR_NAME=""
read_args "$@"
TARGET_DIR_NAME=""
TARGET_DIR_PATH=""
make_target_dir_name_and_path \
	"${B_OPTION:-}"
export TARGET_DIR_NAME=${TARGET_DIR_NAME}
export TARGET_DIR_PATH=${TARGET_DIR_PATH}
[ ! -e "${TARGET_DIR_PATH}" ] && mkdir -p "${TARGET_DIR_PATH}"
cd "${TARGET_DIR_PATH}"
readonly DFBK_IGNORE_FILE_NAME=".difbk_ignore"
readonly DFBK_IGNORE_FILE_PATH="${TARGET_DIR_PATH}/${DFBK_IGNORE_FILE_NAME}"
readonly DFBK_SETTING_DIR_NAME=".difbk_culc"
readonly DFBK_SETTING_DIR_PATH="${HOME}/${DFBK_SETTING_DIR_NAME}"
readonly DFBK_CREATE_CON_PATH="${DFBK_SETTING_DIR_PATH}/create_merge_list"
readonly TARGET_PAR_DIR_PATH=$(dirname ${TARGET_DIR_PATH})
readonly BUCK_UP_DIR_NAME="${OLD_PREFIX}_${TARGET_DIR_NAME}"
readonly BUCK_UP_DIR_PATH="${TARGET_PAR_DIR_PATH}/${BUCK_UP_DIR_NAME}"
readonly BUCKUP_YEAR_DIR_PATH="${BUCK_UP_DIR_PATH}/$(TZ=Asia/Tokyo date '+%Y')"
readonly BUCKUP_MONTH_DIR_PATH="${BUCKUP_YEAR_DIR_PATH}/$(TZ=Asia/Tokyo date '+%m')"
readonly BUCKUP_DAY_DIR_PATH="${BUCKUP_MONTH_DIR_PATH}/$(TZ=Asia/Tokyo date '+%d')"
readonly BUCKUP_TIME_DIR_PATH="${BUCKUP_DAY_DIR_PATH}/$(TZ=Asia/Tokyo date '+%H%M')"

readonly BUCKUP_DESC_FILE_NAME="dfbk_desc.txt"
readonly BUCKUP_DESC_FILE_PATH="${BUCKUP_TIME_DIR_PATH}/${BUCKUP_DESC_FILE_NAME}"

readonly BACKUP_CREATE_DIR_NAME="buckup_create"
readonly BACKUP_CREATE_DIR_PATH="${BUCKUP_TIME_DIR_PATH}/${BACKUP_CREATE_DIR_NAME}"
readonly BUCKUP_MERGE_CONTENSTS_LIST_DIR_NAME="buckup_merge"
readonly BUCKUP_MERGE_CONTENSTS_LIST_DIR_PATH="${BUCKUP_TIME_DIR_PATH}/${BUCKUP_MERGE_CONTENSTS_LIST_DIR_NAME}"
readonly BUCKUP_MERGE_CONTENSTS_LIST_FILE_NAME="buckup_merge_list.txt"
readonly BUCKUP_MERGE_CONTENSTS_LIST_FILE_PATH="${BUCKUP_MERGE_CONTENSTS_LIST_DIR_PATH}/${BUCKUP_MERGE_CONTENSTS_LIST_FILE_NAME}"
readonly SED_TARGET_DIR_PATH=${TARGET_DIR_PATH//\//\\\/}
readonly SED_TARGET_PAR_DIR_PATH=${TARGET_PAR_DIR_PATH//\//\\\/}
readonly SED_BUCK_UP_DIR_PATH=${BUCK_UP_DIR_PATH//\//\\\/}
readonly SED_DFBK_GGIP_EXETEND=${DFBK_GGIP_EXETEND//\./\\\.}
readonly SED_GGIP_EXETEND=${GGIP_EXETEND//\./\\\.}
readonly BUCK_UP_CREATE_DIR_RALATIVE_PATH=${BACKUP_CREATE_DIR_PATH//${SED_TARGET_PAR_DIR_PATH}/}
# ----------------------------------------------------------------
DIFB_SUBCMD_INCLUDE_EJECT=""
# confirm buckup dir ---------------------------------------------
[ ! -e "${DFBK_SETTING_DIR_PATH}" ] && mkdir -p "${DFBK_SETTING_DIR_PATH}"
# ----------------------------------------------------------------
case "${DIFB_SUBCMD_INCLUDE_EJECT}" in
	"") ;;
	*) exit 0
;; esac

case "${DIFBK_SUB_CMD}" in
"${DIFBK_BK_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_bk.sh ;;
"${DIFBK_ST_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_st.sh ;;
"${DIFBK_RS_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_rs.sh ;;
"${DIFBK_CLEAN_CMD_VALIABLE}") 
	LANG="ja_JP.UTF-8" . ${DIFBK_DIR_PATH}/exec_dfbk_clean.sh ;;
"${DIFBK_DIFF_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_diff.sh ;;
"${DIFBK_SCH_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_sch.sh ;;
"${DIFBK_LRS_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_lrs.sh ;;
"${DIFBK_HELP_CMD_VALIABLE}") 
	LANG="ja_JP.UTF-8" . ${DIFBK_DIR_PATH}/exec_dfbk_help.sh ;;
"${DIFBK_MRG_CMD_VALIABLE}") 
	. ${DIFBK_DIR_PATH}/exec_dfbk_mrg.sh ;;
esac
