#!/bin/bash


make_marge_list_file(){
	echo "${LS_BUCKUP_MERGE_CONTENTS}" \
		| sort -k 2,2 \
		| uniq \
		> "${BUCKUP_MERGE_CONTENSTS_LIST_FILE_PATH}"
	gzip ${BUCKUP_MERGE_CONTENSTS_LIST_FILE_PATH} \
		&& mv \
			"${BUCKUP_MERGE_CONTENSTS_LIST_FILE_PATH}${GGIP_EXETEND}" \
			"${BUCKUP_MERGE_CONTENSTS_LIST_FILE_PATH}${DFBK_GGIP_EXETEND}"
}